### PR TITLE
Engine-Campfire: split messages on CR instead of trying to parse

### PR DESCRIPTION
**Pull request by carlosmn**
We currently count the number of braces in order to determine when an
object definition is done. However, this has all sorts of problems
around quoting and strings.

It turns out that the server will send a CR as part of the newline it
sends between each message, which it won't produce inside the objects,
so we can split the message there and be confident that we're passing a
full object to the deserializer.

---

This gets rid of a few issues around pasting code and just makes the whole loop much nicer.

### CODE REVIEW

**Comment by meebey** [comment]
is this issue important enough to go into stable?

**Comment by carlosmn** [comment]
I think so, yeah. If you go with the current code to smuxi's test campfire instance and paste something with closing braces there (like you'll find in there), smuxi will cut off the message and some of the message data will be nonsense.

**Comment by meebey** [comment]
please rebase on stable then

**Comment by carlosmn** [comment]
Done. I can't retarget the pull request, but you can merge this into stable.

**Comment by meebey** [comment]
Merged

**Pull request closed without merging**
